pub mod arity_0 {
    pub use crate::traits::anti_grade::AntiGrade;
    pub use crate::traits::anti_one::AntiOne;
    pub use crate::traits::grade::Grade;
    pub use crate::traits::one::One;
    pub use crate::traits::unit::Unit;
    pub use crate::traits::zero::Zero;
}
pub mod arity_1 {
    pub use crate::traits::anti_auto_morphism::AntiAutoMorphism;
    pub use crate::traits::anti_constraint_valid::AntiConstraintValid;
    pub use crate::traits::anti_constraint_violation::AntiConstraintViolation;
    pub use crate::traits::anti_fix::AntiFix;
    pub use crate::traits::anti_inverse::AntiInverse;
    pub use crate::traits::anti_reverse::AntiReverse;
    pub use crate::traits::anti_support::AntiSupport;
    pub use crate::traits::auto_morphism::AutoMorphism;
    pub use crate::traits::carrier::Carrier;
    pub use crate::traits::center_norm::CenterNorm;
    pub use crate::traits::center_norm_squared::CenterNormSquared;
    pub use crate::traits::co_carrier::CoCarrier;
    pub use crate::traits::complement::Complement;
    pub use crate::traits::conformal_conjugate::ConformalConjugate;
    pub use crate::traits::conjugation::Conjugation;
    pub use crate::traits::constraint_valid::ConstraintValid;
    pub use crate::traits::constraint_violation::ConstraintViolation;
    pub use crate::traits::double_complement::DoubleComplement;
    pub use crate::traits::fix::Fix;
    pub use crate::traits::flat_bulk::FlatBulk;
    pub use crate::traits::flat_bulk_norm::FlatBulkNorm;
    pub use crate::traits::flat_bulk_norm_squared::FlatBulkNormSquared;
    pub use crate::traits::flat_norm::FlatNorm;
    pub use crate::traits::flat_norm_squared::FlatNormSquared;
    pub use crate::traits::flat_weight::FlatWeight;
    pub use crate::traits::flat_weight_norm::FlatWeightNorm;
    pub use crate::traits::flat_weight_norm_squared::FlatWeightNormSquared;
    pub use crate::traits::inverse::Inverse;
    pub use crate::traits::radius_norm::RadiusNorm;
    pub use crate::traits::radius_norm_squared::RadiusNormSquared;
    pub use crate::traits::reverse::Reverse;
    pub use crate::traits::right_anti_dual::RightAntiDual;
    pub use crate::traits::right_dual::RightDual;
    pub use crate::traits::round_bulk::RoundBulk;
    pub use crate::traits::round_bulk_norm::RoundBulkNorm;
    pub use crate::traits::round_bulk_norm_squared::RoundBulkNormSquared;
    pub use crate::traits::round_norm::RoundNorm;
    pub use crate::traits::round_norm_squared::RoundNormSquared;
    pub use crate::traits::round_weight::RoundWeight;
    pub use crate::traits::round_weight_norm::RoundWeightNorm;
    pub use crate::traits::round_weight_norm_squared::RoundWeightNormSquared;
    pub use crate::traits::support::Support;
    pub use crate::traits::unitize::Unitize;
    pub use crate::traits::unitized_center_norm::UnitizedCenterNorm;
    pub use crate::traits::unitized_center_norm_squared::UnitizedCenterNormSquared;
    pub use crate::traits::unitized_flat_norm::UnitizedFlatNorm;
    pub use crate::traits::unitized_flat_norm_squared::UnitizedFlatNormSquared;
    pub use crate::traits::unitized_radius_norm::UnitizedRadiusNorm;
    pub use crate::traits::unitized_radius_norm_squared::UnitizedRadiusNormSquared;
    pub use crate::traits::unitized_round_norm::UnitizedRoundNorm;
    pub use crate::traits::unitized_round_norm_squared::UnitizedRoundNormSquared;
}
pub mod arity_2 {
    pub use crate::traits::anti_dot_product::AntiDotProduct;
    pub use crate::traits::anti_project_orthogonally_onto::AntiProjectOrthogonallyOnto;
    pub use crate::traits::anti_project_via_horizon_onto::AntiProjectViaHorizonOnto;
    pub use crate::traits::anti_reject_orthogonally_from::AntiRejectOrthogonallyFrom;
    pub use crate::traits::anti_reject_via_horizon_from::AntiRejectViaHorizonFrom;
    pub use crate::traits::anti_sandwich::AntiSandwich;
    pub use crate::traits::anti_wedge::AntiWedge;
    pub use crate::traits::bulk_contraction::BulkContraction;
    pub use crate::traits::bulk_expansion::BulkExpansion;
    pub use crate::traits::dot_product::DotProduct;
    pub use crate::traits::geometric_anti_product::GeometricAntiProduct;
    pub use crate::traits::geometric_anti_quotient::GeometricAntiQuotient;
    pub use crate::traits::geometric_product::GeometricProduct;
    pub use crate::traits::geometric_quotient::GeometricQuotient;
    pub use crate::traits::project_orthogonally_onto::ProjectOrthogonallyOnto;
    pub use crate::traits::project_via_origin_onto::ProjectViaOriginOnto;
    pub use crate::traits::reject_orthogonally_from::RejectOrthogonallyFrom;
    pub use crate::traits::reject_via_origin_from::RejectViaOriginFrom;
    pub use crate::traits::sandwich::Sandwich;
    pub use crate::traits::wedge::Wedge;
    pub use crate::traits::weight_contraction::WeightContraction;
    pub use crate::traits::weight_expansion::WeightExpansion;
}
mod anti_auto_morphism;
pub use anti_auto_morphism::AntiAutoMorphism;
mod anti_constraint_valid;
pub use anti_constraint_valid::AntiConstraintValid;
mod anti_constraint_violation;
pub use anti_constraint_violation::AntiConstraintViolation;
mod anti_dot_product;
pub use anti_dot_product::AntiDotProduct;
mod anti_fix;
pub use anti_fix::AntiFix;
mod anti_grade;
pub use anti_grade::AntiGrade;
mod anti_inverse;
pub use anti_inverse::AntiInverse;
mod anti_one;
pub use anti_one::AntiOne;
mod anti_project_orthogonally_onto;
pub use anti_project_orthogonally_onto::AntiProjectOrthogonallyOnto;
mod anti_project_via_horizon_onto;
pub use anti_project_via_horizon_onto::AntiProjectViaHorizonOnto;
mod anti_reject_orthogonally_from;
pub use anti_reject_orthogonally_from::AntiRejectOrthogonallyFrom;
mod anti_reject_via_horizon_from;
pub use anti_reject_via_horizon_from::AntiRejectViaHorizonFrom;
mod anti_reverse;
pub use anti_reverse::AntiReverse;
mod anti_sandwich;
pub use anti_sandwich::AntiSandwich;
mod anti_support;
pub use anti_support::AntiSupport;
mod anti_wedge;
pub use anti_wedge::AntiWedge;
mod auto_morphism;
pub use auto_morphism::AutoMorphism;
mod bulk_contraction;
pub use bulk_contraction::BulkContraction;
mod bulk_expansion;
pub use bulk_expansion::BulkExpansion;
mod carrier;
pub use carrier::Carrier;
mod center_norm;
pub use center_norm::CenterNorm;
mod center_norm_squared;
pub use center_norm_squared::CenterNormSquared;
mod co_carrier;
pub use co_carrier::CoCarrier;
mod complement;
pub use complement::Complement;
mod conformal_conjugate;
pub use conformal_conjugate::ConformalConjugate;
mod conjugation;
pub use conjugation::Conjugation;
mod constraint_valid;
pub use constraint_valid::ConstraintValid;
mod constraint_violation;
pub use constraint_violation::ConstraintViolation;
mod dot_product;
pub use dot_product::DotProduct;
mod double_complement;
pub use double_complement::DoubleComplement;
mod fix;
pub use fix::Fix;
mod flat_bulk;
pub use flat_bulk::FlatBulk;
mod flat_bulk_norm;
pub use flat_bulk_norm::FlatBulkNorm;
mod flat_bulk_norm_squared;
pub use flat_bulk_norm_squared::FlatBulkNormSquared;
mod flat_norm;
pub use flat_norm::FlatNorm;
mod flat_norm_squared;
pub use flat_norm_squared::FlatNormSquared;
mod flat_weight;
pub use flat_weight::FlatWeight;
mod flat_weight_norm;
pub use flat_weight_norm::FlatWeightNorm;
mod flat_weight_norm_squared;
pub use flat_weight_norm_squared::FlatWeightNormSquared;
mod geometric_anti_product;
pub use geometric_anti_product::GeometricAntiProduct;
mod geometric_anti_quotient;
pub use geometric_anti_quotient::GeometricAntiQuotient;
mod geometric_product;
pub use geometric_product::GeometricProduct;
mod geometric_quotient;
pub use geometric_quotient::GeometricQuotient;
mod grade;
pub use grade::Grade;
mod inverse;
pub use inverse::Inverse;
mod one;
pub use one::One;
mod project_orthogonally_onto;
pub use project_orthogonally_onto::ProjectOrthogonallyOnto;
mod project_via_origin_onto;
pub use project_via_origin_onto::ProjectViaOriginOnto;
mod radius_norm;
pub use radius_norm::RadiusNorm;
mod radius_norm_squared;
pub use radius_norm_squared::RadiusNormSquared;
mod reject_orthogonally_from;
pub use reject_orthogonally_from::RejectOrthogonallyFrom;
mod reject_via_origin_from;
pub use reject_via_origin_from::RejectViaOriginFrom;
mod reverse;
pub use reverse::Reverse;
mod right_anti_dual;
pub use right_anti_dual::RightAntiDual;
mod right_dual;
pub use right_dual::RightDual;
mod round_bulk;
pub use round_bulk::RoundBulk;
mod round_bulk_norm;
pub use round_bulk_norm::RoundBulkNorm;
mod round_bulk_norm_squared;
pub use round_bulk_norm_squared::RoundBulkNormSquared;
mod round_norm;
pub use round_norm::RoundNorm;
mod round_norm_squared;
pub use round_norm_squared::RoundNormSquared;
mod round_weight;
pub use round_weight::RoundWeight;
mod round_weight_norm;
pub use round_weight_norm::RoundWeightNorm;
mod round_weight_norm_squared;
pub use round_weight_norm_squared::RoundWeightNormSquared;
mod sandwich;
pub use sandwich::Sandwich;
mod support;
pub use support::Support;
mod unit;
pub use unit::Unit;
mod unitize;
pub use unitize::Unitize;
mod unitized_center_norm;
pub use unitized_center_norm::UnitizedCenterNorm;
mod unitized_center_norm_squared;
pub use unitized_center_norm_squared::UnitizedCenterNormSquared;
mod unitized_flat_norm;
pub use unitized_flat_norm::UnitizedFlatNorm;
mod unitized_flat_norm_squared;
pub use unitized_flat_norm_squared::UnitizedFlatNormSquared;
mod unitized_radius_norm;
pub use unitized_radius_norm::UnitizedRadiusNorm;
mod unitized_radius_norm_squared;
pub use unitized_radius_norm_squared::UnitizedRadiusNormSquared;
mod unitized_round_norm;
pub use unitized_round_norm::UnitizedRoundNorm;
mod unitized_round_norm_squared;
pub use unitized_round_norm_squared::UnitizedRoundNormSquared;
mod wedge;
pub use wedge::Wedge;
mod weight_contraction;
pub use weight_contraction::WeightContraction;
mod weight_expansion;
pub use weight_expansion::WeightExpansion;
mod zero;
pub use zero::Zero;
