implementing cga3d;
// Fancy postfix trick
public AntiCircleRotor operator /(AntiCircleRotor lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiCircleRotor operator /(DoubleComplementPrefixOrPostfix lhs, AntiCircleRotor rhs) {
    return rhs.double_complement();
}
public extension AntiCircleRotor {
    public AntiCircleRotor double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiDipoleInversion operator /(AntiDipoleInversion lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiDipoleInversion operator /(DoubleComplementPrefixOrPostfix lhs, AntiDipoleInversion rhs) {
    return rhs.double_complement();
}
public extension AntiDipoleInversion {
    public AntiDipoleInversion double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiDualNum operator /(AntiDualNum lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiDualNum operator /(DoubleComplementPrefixOrPostfix lhs, AntiDualNum rhs) {
    return rhs.double_complement();
}
public extension AntiDualNum {
    public AntiDualNum double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiFlatPoint operator /(AntiFlatPoint lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiFlatPoint operator /(DoubleComplementPrefixOrPostfix lhs, AntiFlatPoint rhs) {
    return rhs.double_complement();
}
public extension AntiFlatPoint {
    public AntiFlatPoint double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiFlector operator /(AntiFlector lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiFlector operator /(DoubleComplementPrefixOrPostfix lhs, AntiFlector rhs) {
    return rhs.double_complement();
}
public extension AntiFlector {
    public AntiFlector double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiLine operator /(AntiLine lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiLine operator /(DoubleComplementPrefixOrPostfix lhs, AntiLine rhs) {
    return rhs.double_complement();
}
public extension AntiLine {
    public AntiLine double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiMotor operator /(AntiMotor lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiMotor operator /(DoubleComplementPrefixOrPostfix lhs, AntiMotor rhs) {
    return rhs.double_complement();
}
public extension AntiMotor {
    public AntiMotor double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiPlane operator /(AntiPlane lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiPlane operator /(DoubleComplementPrefixOrPostfix lhs, AntiPlane rhs) {
    return rhs.double_complement();
}
public extension AntiPlane {
    public AntiPlane double_complement() {
        return this;
    }
}
// Fancy postfix trick
public AntiScalar operator /(AntiScalar lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public AntiScalar operator /(DoubleComplementPrefixOrPostfix lhs, AntiScalar rhs) {
    return rhs.double_complement();
}
public extension AntiScalar {
    public AntiScalar double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Circle operator /(Circle lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Circle operator /(DoubleComplementPrefixOrPostfix lhs, Circle rhs) {
    return rhs.double_complement();
}
public extension Circle {
    public Circle double_complement() {
        return this;
    }
}
// Fancy postfix trick
public CircleRotor operator /(CircleRotor lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public CircleRotor operator /(DoubleComplementPrefixOrPostfix lhs, CircleRotor rhs) {
    return rhs.double_complement();
}
public extension CircleRotor {
    public CircleRotor double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Dipole operator /(Dipole lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Dipole operator /(DoubleComplementPrefixOrPostfix lhs, Dipole rhs) {
    return rhs.double_complement();
}
public extension Dipole {
    public Dipole double_complement() {
        return this;
    }
}
// Fancy postfix trick
public DipoleInversion operator /(DipoleInversion lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public DipoleInversion operator /(DoubleComplementPrefixOrPostfix lhs, DipoleInversion rhs) {
    return rhs.double_complement();
}
public extension DipoleInversion {
    public DipoleInversion double_complement() {
        return this;
    }
}
// Fancy postfix trick
public DualNum operator /(DualNum lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public DualNum operator /(DoubleComplementPrefixOrPostfix lhs, DualNum rhs) {
    return rhs.double_complement();
}
public extension DualNum {
    public DualNum double_complement() {
        return this;
    }
}
// Fancy postfix trick
public FlatPoint operator /(FlatPoint lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public FlatPoint operator /(DoubleComplementPrefixOrPostfix lhs, FlatPoint rhs) {
    return rhs.double_complement();
}
public extension FlatPoint {
    public FlatPoint double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Flector operator /(Flector lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Flector operator /(DoubleComplementPrefixOrPostfix lhs, Flector rhs) {
    return rhs.double_complement();
}
public extension Flector {
    public Flector double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Line operator /(Line lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Line operator /(DoubleComplementPrefixOrPostfix lhs, Line rhs) {
    return rhs.double_complement();
}
public extension Line {
    public Line double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Motor operator /(Motor lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Motor operator /(DoubleComplementPrefixOrPostfix lhs, Motor rhs) {
    return rhs.double_complement();
}
public extension Motor {
    public Motor double_complement() {
        return this;
    }
}
// Fancy postfix trick
public MultiVector operator /(MultiVector lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public MultiVector operator /(DoubleComplementPrefixOrPostfix lhs, MultiVector rhs) {
    return rhs.double_complement();
}
public extension MultiVector {
    public MultiVector double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Plane operator /(Plane lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Plane operator /(DoubleComplementPrefixOrPostfix lhs, Plane rhs) {
    return rhs.double_complement();
}
public extension Plane {
    public Plane double_complement() {
        return this;
    }
}
// Fancy postfix trick
public RoundPoint operator /(RoundPoint lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public RoundPoint operator /(DoubleComplementPrefixOrPostfix lhs, RoundPoint rhs) {
    return rhs.double_complement();
}
public extension RoundPoint {
    public RoundPoint double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Scalar operator /(Scalar lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Scalar operator /(DoubleComplementPrefixOrPostfix lhs, Scalar rhs) {
    return rhs.double_complement();
}
public extension Scalar {
    public Scalar double_complement() {
        return this;
    }
}
// Fancy postfix trick
public Sphere operator /(Sphere lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public Sphere operator /(DoubleComplementPrefixOrPostfix lhs, Sphere rhs) {
    return rhs.double_complement();
}
public extension Sphere {
    public Sphere double_complement() {
        return this;
    }
}
// Fancy postfix trick
public VersorEven operator /(VersorEven lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public VersorEven operator /(DoubleComplementPrefixOrPostfix lhs, VersorEven rhs) {
    return rhs.double_complement();
}
public extension VersorEven {
    public VersorEven double_complement() {
        return this;
    }
}
// Fancy postfix trick
public VersorOdd operator /(VersorOdd lhs, DoubleComplementPrefixOrPostfix rhs)  {
    return lhs.double_complement();
    }
// Fancy prefix trick
public VersorOdd operator /(DoubleComplementPrefixOrPostfix lhs, VersorOdd rhs) {
    return rhs.double_complement();
}
public extension VersorOdd {
    public VersorOdd double_complement() {
        return this;
    }
}
