[package]
name = "codegen"
version = "0.3.0"
authors = ["Alexander Meißner <AlexanderMeissner@gmx.net>", "Andrew Brown <Andrew.Brown.UNL@gmail.com>"]
description = "Generate(d) custom libraries for geometric algebras"
repository = "https://github.com/AndrewBrownK/projective_ga/"
keywords = ["math", "simd", "vector", "geometric-algebra", "geometry"]
license = "MIT"
edition = "2021"
publish = false

[features]
default = []
large-basis-elements = []
very-large-basis-elements = ["large-basis-elements"]
# TODO clean up this feature
incorrect-wip-traits = []

[dependencies]
#naga = { version = "0.20.0", features = ["default", "glsl-in", "wgsl-in"] }
anyhow = "1.0.81"
parking_lot = "0.12.2"
bitflags = "2.5.0"
async-trait = "0.1.80"
rand = "0.9.0-alpha.1"
regex = "1.10.4"
lazy_static = "1.4.0"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "io-std", "io-util", "sync", "signal", "fs", "parking_lot", "time", "macros"] }
im = "15.1.0"
either = "1.12.0"
atom = "0.4.0"
paste = "1.0.15"
const_panic = { version = "0.2.8", features = ["default", "derive"] }
indicatif = "0.17.8"
float-ord = "0.3.2"

# todo I think I only have these for simd.rs, so I might rather remove this dependency and do that differently
encase = "0.9.0"
nearly = "0.4.0"

tracing = "0.1.41"
tracing-subscriber = "0.3.19"
once_cell = "1.20.2"

#bitvec = "1.0.1"

# What is our preferred Copy and const imitation Vec?

# tinyvec is nice but doesn't offer enough const evaluation support
# (can still use it for other situations besides MultiVec BasisElementGroups)
tinyvec = { version = "1.6.0", features = ["alloc", "rustc_1_57"] }

# construe seems extremely nice, but I think I can know the sizes of my arrays, and I definitely want to read
# arrays as I'm constructing them so that for example there is not duplicate BasisElements in a MultiVec
# So even though it seems really cool, it might not be right for my situation
#construe = "0.0.3"

# const-vec lets you specify the size, which is fine by me, and also allows slice indexing and iteration and stuff.
# The problem is that it is the wrong meaning of "const". It is const as in interior mutability, not const
# as in const evaluation.
#const-vec = "1.1.1"

# inline-const seems to offer cool stuff, worth checking out, but doesn't seem like the most straightforward
# solution to my current problem (MultiVecs)
#inline-const = "0.1.0"

# const-gen is also cool but seems heavily oriented towards build-rs, which is not what I'm aiming for right now
#const-gen = "1.6.4"

# These strangers seem categorically on-topic, but too sparse on documentation to commit
#const_std_vec = "0.2.0"

# Conclusion..... I have to roll my own